ORIGAMI_DEVICE := $(shell echo "$(TARGET_PRODUCT)" | cut -d '_' -f 2,3)
ORIGAMI_VERSION_NO := 1.0
ORIGAMI_CODENAME := Tengu
ORIGAMI_BUILD_DATE := $(shell date -u +%Y%m%d)

ORIGAMI_VERSION_SUFFIX := origamiOS-$(ORIGAMI_VERSION)

# Internal version
ifneq ($(ORIGAMI_VERSIONTYPE), beta)
    ORIGAMI_VERSION := $(ORIGAMI_VERSION_NO)-$(ORIGAMI_CODENAME)-$(ORIGAMI_VERSIONTYPE)-$(ORIGAMI_BUILD_DATE)-$(ORIGAMI_BUILDTYPE)
else
    ORIGAMI_VERSION := $(ORIGAMI_VERSION_NO)-$(ORIGAMI_CODENAME)-$(ORIGAMI_BUILD_DATE)-$(ORIGAMI_BUILDTYPE)
endif

# Display version
ifneq ($(ORIGAMI_VERSIONTYPE), beta)
    ORIGAMI_DISPLAY_VERSION := $(ORIGAMI_VERSION_NO) | $(ORIGAMI_CODENAME) ($(ORIGAMI_VERSIONTYPE))
else
    ORIGAMI_DISPLAY_VERSION := $(ORIGAMI_VERSION_NO) | $(ORIGAMI_CODENAME)

endif
